# SPDX-FileCopyrightText: 2025 Max Reznik <reznikmm@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Build with Alire

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: alire-project/setup-alire@v5
      with:
        toolchain: 'gnat_arm_elf gprbuild'
    - name: Build project and demos
      run: alr test
    - name: Dump log
      if: ${{ failure() }}
      run: cat alire/alr_test_local.log
